name = "ozoboom-turn"
main = "src/index.ts"
compatibility_date = "2026-10-01"

[triggers]
crons = ["*/10 * * * *"]

[[kv_namespaces]]
binding = "USAGE"
id = "04d30881c5c24ce7bba0d23f1a4eb2a2"

[[ratelimits]]
name = "RATE_LIMIT"
namespace_id = "1001"
simple = { limit = 20, period = 60 }
